import { useContext } from "react";
import { useRouter } from 'next/router';
import { DetailContext } from '../context/DetailProvider';
import Head from "next/head";
import { Box, Card, Typography, Stack, Grid, InputBase } from "@mui/material";
import { convertDate } from "..";

const NewsDetail = () => {
  const router = useRouter();
  const { slug } = router.query;
  const { data } = useContext(DetailContext);

  return (
    <>
      <Head>
        <title>{data.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box className="detail-news">
        <Box
          sx={{
            p: 0,
            display: 'flex',
            flexDirection: 'column',
            marginBottom: '1.5rem',
            borderBottom: '1px solid #eee',
            paddingBottom: '1.5rem'
          }}>
          <img className="detail-news-card-image" src={data.imageUrl} alt={data.name} />
          <Stack sx={{p: 0}} spacing={2}>
            {
              data.topics.map(itemTopic => {
                return(
                  <Typography key={itemTopic.id} className="topic">
                    {itemTopic.title}
                  </Typography>
                )
              })
            }
            <Typography style={{cursor: 'pointer'}} fontWeight={700}>{data.name}</Typography>
            <Typography className="description">{data.description}</Typography>
            <Box sx={{display: 'flex', alignItems: 'center'}}>
              <Typography className="date">{convertDate(data.publicationDate)}</Typography>
              <span>&nbsp;&nbsp;|&nbsp;&nbsp;</span>
              {
                data.organization.map(itemOrganization => {
                  return(
                    <Typography key={itemOrganization.fields.slug} className="organization">{itemOrganization.fields.name}</Typography>
                  )
                })
              }
            </Box>
          </Stack>
        </Box>
      </Box>
    </>
  );
};

export default NewsDetail;